### ISSUE TITLE
Ruggedcom Syntax Highlighting

### ISSUE THREAD

**Issue by ryandenyer** [cbspace/VSCodeExtensions#2]
When assigning the location of Portsmith into the config "Port" is changed to blue.

![Screenshot 2024-07-12 111213](https://github.com/user-attachments/assets/5f28bafd-f349-4861-a00c-7e4a6e7516e6)

**Comment by cbspace** [comment]
Fixed in [this commit](https://github.com/cbspace/VSCodeExtensions/commit/e260132fe267944e0fb27558703d70c78a091399), Ruggedcom Packaged V0.0.4

Other issues fixed:
- The word "Port" is no longer highlighted in "Port 1/2/3/4" 
- The "32" integer in "RSTP (32 bit)" is no longer highlighted
